site_name: Skforecast Docs
extra_css:
  - stylesheets/extra.css
repo_url: https://github.com/JoaquinAmatRodrigo/skforecast
site_url: https://joaquinamatrodrigo.github.io/skforecast/
site_description: Python library that eases using scikit-learn regressors as multi-step forecasters. It also works with any regressor compatible with the scikit-learn API (XGBoost, LightGBM, Ranger...).
site_author: Joaquin Amat Rodrigo and Javier Escobar Ortiz
use_directory_urls: false
nav:
  - Home:
    - Welcome to skforecast: README.md
    - Quick start: quick-start/introduction-forecasting.md
    - User Guides: user_guides/input-data.ipynb
    - Examples and tutorials: examples/examples.md
    - API Reference: api/ForecasterAutoreg.md
    - FAQ and Tips: faq/profiling-skforecast.ipynb
    - Releases: releases/releases.md

  - Quick start:
    - Introduction to forecasting: quick-start/introduction-forecasting.md
    - Quick start skforecast: user_guides/quick-start-skforecast.ipynb

  - User Guides:
      - Input data: user_guides/input-data.ipynb
      - Recursive multi-step forecasting: user_guides/autoregresive-forecaster.ipynb
      - Direct multi-step forecasting: user_guides/direct-multi-step-forecasting.ipynb
      - Multi-time series forecasting: user_guides/multi-time-series-forecasting.ipynb
      - Exogenous variables: user_guides/autoregresive-forecaster-exogenous.ipynb
      - Custom predictors: user_guides/custom-predictors.ipynb
      - Forecasting with weights: user_guides/forecasting-with-weights.ipynb
      - Backtesting forecaster: user_guides/backtesting.ipynb
      - Hyperparameter tuning and lags selection: user_guides/hyperparameter-tuning-and-lags-selection.ipynb
      - Scikit-learn Transformers and Pipelines: user_guides/sklearn-transformers-and-pipeline.ipynb
      - Prediction intervals: user_guides/prediction-intervals.ipynb
      - Feature importance: user_guides/feature-importance.ipynb
      - Forecasting with XGBoost: user_guides/forecasting-xgboost.ipynb
      - Save and load forecaster: user_guides/save-load-forecaster.ipynb
      - Forecaster in production: user_guides/forecaster-in-production.ipynb
      - Grid search SARIMAX and ARIMA models: user_guides/grid-search-sarimax-arima.ipynb
      - Backtesting SARIMAX and ARIMA models: user_guides/backtesting-sarimax-arima.ipynb
      - Plot forecaster residuals: user_guides/plot-forecaster-residuals.ipynb

  - Examples and tutorials:
      - Examples and tutorials: examples/examples.md

  - API Reference:
      - ForecasterAutoreg: api/ForecasterAutoreg.md
      - ForecasterAutoregCustom: api/ForecasterAutoregCustom.md
      - ForecasterAutoregDirect: api/ForecasterAutoregDirect.md
      - ForecasterMultiSeries: api/ForecasterMultiSeries.md
      - model_selection: api/model_selection.md
      - model_selection_multiseries: api/model_selection_multiseries.md
      - model_selection_statsmodels: api/model_selection_statsmodels.md
      - plot: api/plot.md
      - utils: api/utils.md

  - FAQ and Tips:
      - Profiling skforecast: faq/profiling-skforecast.ipynb
      - Avoid negative predictions when forecasting: faq/non-negative-predictions.ipynb
      #- Single series vs multi series forecasting: faq/single-vs-multi-series-forecasting.ipynb

  - Releases: releases/releases.md

plugins:
  - mkdocstrings:
      handlers:
        python:
          selection:
            docstring_style: numpy
            filters:
              - "!^_"  # exclude all members starting with _
          rendering:
            show_root_heading: True
            show_root_full_path: False
            docstring_section_style: table
  - mkdocs-jupyter:
      ignore_h1_titles: True
      include_source: True
      execute: False
      allow_errors: False
  - search
copyright: 
theme:
  name: material
  custom_dir: docs/overrides
  font:
    text: Ubuntu
    code: Ubuntu Mono
  logo: img/logo_skforecast_white_no_background.png
  highlightjs: true
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.expand
    - navigation.top
  palette:
    primary: deep purple
    accent: light blue
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - codehilite
  - pymdownx.inlinehilite
  - pymdownx.details
  - pymdownx.tabbed
  - pymdownx.highlight:
      use_pygments: true
      linenums: true
  - pymdownx.superfences
  - pymdownx.magiclink
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - toc:
      permalink: true
extra:
  version:
    provider: mike
  analytics:
    provider: google
    property: G-GR8X9Z9LKL
  consent:
    title: Cookie consent
    description: >- 
      We use cookies to recognize your repeated visits and preferences, as well
      as to measure the effectiveness of our documentation and whether users
      find what they're searching for. With your consent, you're helping us to
      make our documentation better.