site_name: Skforecast Docs
extra_css:
  - stylesheets/extra.css
repo_url: https://github.com/JoaquinAmatRodrigo/skforecast
site_url: https://joaquinamatrodrigo.github.io/skforecast/
site_description: Python library that eases using scikit-learn regressors as multi-step forecasters. It also works with any regressor compatible with the scikit-learn API (XGBoost, LightGBM, Ranger...).
site_author: Joaquin Amat Rodrigo and Javier Escobar Ortiz
use_directory_urls: false
copyright: Copyright &copy; 2021 - 2024 JoaquÃ­n Amat Rodrigo, Javier Escobar Ortiz

nav:
  - Home:
    - Welcome to skforecast: README.md
    - Introduction to forecasting: introduction-forecasting/introduction-forecasting.md
    - Quick start: user_guides/quick-start-skforecast.ipynb
    - User Guides: user_guides/input-data.ipynb
    - Examples and tutorials: examples/examples.md
    - API Reference: api/ForecasterAutoreg.md
    - FAQ and Tips: faq/faq.md
    - Releases: releases/releases.md

  - Introduction to forecasting: 
    - Introduction to forecasting: introduction-forecasting/introduction-forecasting.md

  - Quick start:
    - Quick start: user_guides/quick-start-skforecast.ipynb
    - Forecaster Parameters: introduction-forecasting/forecaster-parameters.md
    - Forecaster Attributes: introduction-forecasting/forecaster-attributes.ipynb

  - User Guides:
      - Input data: user_guides/input-data.ipynb
      - Recursive multi-step forecasting: user_guides/autoregresive-forecaster.ipynb
      - Direct multi-step forecasting: user_guides/direct-multi-step-forecasting.ipynb
      - Independent multi-time series forecasting: user_guides/independent-multi-time-series-forecasting.ipynb
      - Series with different lengths and different exogenous variables: user_guides/multi-series-with-different-length-and-different_exog.ipynb
      - Dependent multivariate series forecasting: user_guides/dependent-multi-series-multivariate-forecasting.ipynb
      - Deep learning Recurrent Neural Networks: user_guides/forecasting-with-deep-learning-rnn-lstm.ipynb
      - ARIMA and SARIMAX forecasting: user_guides/forecasting-sarimax-arima.ipynb
      - Foreasting baseline: user_guides/forecasting-baseline.ipynb
      - Exogenous variables: user_guides/exogenous-variables.ipynb
      - Custom predictors: user_guides/custom-predictors.ipynb
      - Weighted time series forecasting: user_guides/weighted-time-series-forecasting.ipynb
      - Backtesting forecaster: user_guides/backtesting.ipynb
      - Hyperparameter tuning and lags selection: user_guides/hyperparameter-tuning-and-lags-selection.ipynb
      - Scikit-learn Transformers and Pipelines: user_guides/sklearn-transformers-and-pipeline.ipynb
      - Probabilistic forecasting: user_guides/probabilistic-forecasting.ipynb
      - Categorical features: user_guides/categorical-features.ipynb
      - Calendars features: user_guides/calendar-features.ipynb
      - Feature selection: user_guides/feature-selection.ipynb
      - Forecasting with XGBoost and LightGBM: user_guides/forecasting-xgboost-lightgbm.ipynb
      - Forecaster in production: user_guides/forecaster-in-production.ipynb
      - Save and load forecaster: user_guides/save-load-forecaster.ipynb
      - Explainability: user_guides/explainability.ipynb
      - Skforecast in GPU: user_guides/skforecast-in-GPU.ipynb
      - Plot forecaster residuals: user_guides/plot-forecaster-residuals.ipynb
      - Datasets: user_guides/datasets.ipynb

  - Examples and tutorials:
      - Examples and tutorials: examples/examples.md

  - API Reference:
      - ForecasterAutoreg: api/ForecasterAutoreg.md
      - ForecasterAutoregCustom: api/ForecasterAutoregCustom.md
      - ForecasterAutoregDirect: api/ForecasterAutoregDirect.md
      - ForecasterMultiSeries: api/ForecasterMultiSeries.md
      - ForecasterMultiSeriesCustom: api/ForecasterMultiSeriesCustom.md
      - ForecasterMultiVariate: api/ForecasterMultiVariate.md
      - ForecasterRnn: api/ForecasterRnn.md
      - ForecasterSarimax: api/ForecasterSarimax.md
      - Sarimax: api/Sarimax.md
      - ForecasterBaseline: api/ForecasterBaseline.md
      - model_selection: api/model_selection.md
      - model_selection_multiseries: api/model_selection_multiseries.md
      - model_selection_sarimax: api/model_selection_sarimax.md
      - preprocessing: api/preprocessing.md
      - plot: api/plot.md
      - utils: api/utils.md
      - datasets: api/datasets.md
      - exceptions: api/exceptions.md

  - FAQ and Tips:
      - Table of contents: faq/faq.md
      - Time series differentiation: faq/time-series-differentiation.ipynb
      - Avoid negative predictions when forecasting: faq/non-negative-predictions.ipynb
      - Forecasting time series with missing values: faq/forecasting-time-series-with-missing-values.ipynb
      - Cyclical features in time series: faq/cyclical-features-time-series.ipynb
      - Stacking (ensemble) machine learning models: faq/stacking-ensemble-models-forecasting.ipynb
      - Forecasting with delayed historical data: faq/forecasting-with-delayed-historical-data.ipynb
      - Time series aggregation: faq/time-series-aggregation.ipynb
      - Parallelization in skforecast: faq/parallelization-skforecast.ipynb
      - Profiling skforecast: faq/profiling-skforecast.ipynb

  - Releases: releases/releases.md

  - Authors: authors/authors.md

plugins:
  - mkdocstrings:
      handlers:
        python:
          options:
            docstring_style: numpy
            docstring_section_style: table
            show_root_heading: true
            show_root_full_path: false
            merge_init_into_class: true
            filters: ["!__"] # exclude all members starting with __
            members_order: source
            docstring_options:
              ignore_init_summary: true
  - mkdocs-jupyter:
      ignore_h1_titles: True
      include_source: True
      execute: False
      allow_errors: False
      include_requirejs: True
  - search

theme:
  name: material
  custom_dir: docs/overrides
  font:
    text: Open Sans
    code: Ubuntu Mono
  logo: img/logo-skforecast-orange-no-backgound.png
  favicon: img/favicon.png
  highlightjs: true
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.expand
    - navigation.top
  palette:
    # # Palette toggle for automatic mode
    # - media: "(prefers-color-scheme)"
    #   primary: custom
    #   accent: custom
    #   toggle:
    #     icon: material/brightness-auto
    #     name: Switch to light mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: light
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - codehilite
  - pymdownx.inlinehilite
  - pymdownx.details
  - pymdownx.tabbed
  - pymdownx.highlight:
      use_pygments: true
      linenums: true
  - pymdownx.superfences
  - pymdownx.magiclink
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - toc:
      permalink: true
extra:
  version:
    provider: mike
  analytics:
    provider: google
    property: G-GR8X9Z9LKL
  consent:
    title: Cookie consent
    description: >- 
      We use cookies to recognize your repeated visits and preferences, as well
      as to measure the effectiveness of our documentation and whether users
      find what they're searching for. With your consent, you're helping us to
      make our documentation better.