site_name: Skforecast Docs
extra_css:
  - stylesheets/extra.css
repo_url: https://github.com/JoaquinAmatRodrigo/skforecast
site_url: https://joaquinamatrodrigo.github.io/skforecast/
site_description: Python library that eases using scikit-learn regressors as multi-step forecasters. It also works with any regressor compatible with the scikit-learn API (XGBoost, LightGBM, Ranger...).
site_author: Joaquin Amat Rodrigo
use_directory_urls: false
nav:
  - Home:
    - Welcome to skforecast: README.md
    - Introduction to forecasting: quick-start/introduction-forecasting.md
    - User Guides: notebooks/input-data.ipynb
    - Examples and tutorials: examples/examples.md
    - API Reference: api/ForecasterAutoreg.md
    - Releases: releases/releases.md

  - Quick start:
    - Introduction to forecasting: quick-start/introduction-forecasting.md
    - Quick start skforecast: notebooks/quick-start-skforecast.ipynb

  - User Guides:
      - Input data: notebooks/input-data.ipynb
      - Recursive multi-step forecasting: notebooks/autoregresive-forecaster.ipynb
      - Direct multi-step forecasting: notebooks/direct-multi-step-forecasting.ipynb
      - Exogenous variables: notebooks/autoregresive-forecaster-exogenous.ipynb
      - Custom predictors: notebooks/custom-predictors.ipynb
      - Backtesting forecaster: notebooks/backtesting.ipynb
      - Grid search forecaster: notebooks/grid-search-forecaster.ipynb
      - Scikit-learn Pipeline: notebooks/sklearn-pipeline.ipynb
      - Prediction intervals: notebooks/prediction-intervals.ipynb
      - Feature importance: notebooks/feature-importance.ipynb
      - Forecasting with XGBoost: notebooks/forecasting-xgboost.ipynb
      - Save and load forecaster: notebooks/save-load-forecaster.ipynb
      - Forecaster in production: notebooks/forecaster-in-production.ipynb
      - Grid search SARIMAX and ARIMA models: notebooks/grid-search-sarimax-arima.ipynb
      - Backtesting SARIMAX and ARIMA models: notebooks/backtesting-sarimax-arima.ipynb

  - Examples and tutorials:
      - Examples and tutorials: examples/examples.md

  - API Reference:
      - ForecasterAutoreg: api/ForecasterAutoreg.md
      - ForecasterAutoregCustom: api/ForecasterAutoregCustom.md
      - ForecasterAutoregMultiOutput: api/ForecasterAutoregMultiOutput.md
      - model_selection: api/model_selection.md
      - model_selection_statsmodels: api/model_selection_statsmodels.md

  - Releases: releases/releases.md

plugins:
  - mkdocstrings:
      handlers:
        python:
          selection:
            docstring_style: numpy
            filters:
              - "!^_"  # exclude all members starting with _
          rendering:
            show_root_heading: yes
            docstring_section_style: table
  # - mknotebooks:
  #     enable_default_jupyter_cell_styling: false
  #     enable_default_pandas_dataframe_styling: true
  - mkdocs-jupyter:
      include_source: False
      ignore_h1_titles: True
      include_source: True
  - search
copyright: 
theme:
  name: material
  font:
    text: Ubuntu
    code: Ubuntu Mono
  logo: img/logo_skforecast_white_no_background.png
  highlightjs: true
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.expand
    - navigation.top
  palette:
    primary: deep purple
    accent: light blue
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - codehilite
  - pymdownx.inlinehilite
  - pymdownx.details
  - pymdownx.tabbed
  - pymdownx.highlight:
      use_pygments: true
      linenums: true
  - pymdownx.superfences
  - pymdownx.magiclink
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - toc:
      permalink: true
extra:
  version:
    provider: mike